#!/usr/bin/env bash

echo "========================================="
echo "IVS Multi-Disease System - Chain Setup"
echo "========================================="
echo ""
echo "IMPORTANT: Building the chains takes 30-60 minutes!"
echo ""
echo "Current status:"
echo "  ✓ Worker is functional (demo completed successfully)"
echo "  ✓ Pallet code is ready in pallets/ivs/"
echo "  ✓ Scripts are ready to launch chains"
echo "  ✓ polkadot-sdk symlink is in place"
echo ""
echo "To run the full blockchain network, follow these steps:"
echo ""
echo "========================================="
echo "Step 1: Build Everything (30-60 min)"
echo "========================================="
echo ""
echo "  make build"
echo ""
echo "This will:"
echo "  - Build relay chain (polkadot)"
echo "  - Copy polkadot-parachain template 3 times"
echo "  - Build disease-a parachain"
echo "  - Build disease-b parachain"
echo "  - Build aggregator parachain"
echo ""
echo "========================================="
echo "Step 2: Start Chains (4 terminals)"
echo "========================================="
echo ""
echo "Terminal 1 - Relay Chain:"
echo "  make relay"
echo ""
echo "Terminal 2 - Disease-A Parachain (ParaId: 2000):"
echo "  make para-a"
echo ""
echo "Terminal 3 - Disease-B Parachain (ParaId: 2001):"
echo "  make para-b"
echo ""
echo "Terminal 4 - Aggregator Parachain (ParaId: 3000):"
echo "  make para-agg"
echo ""
echo "========================================="
echo "Step 3: Export & Register Parachains"
echo "========================================="
echo ""
echo "Export genesis artifacts:"
echo "  make export"
echo ""
echo "Register parachains via Polkadot.js Apps:"
echo "  make register"
echo ""
echo "Or use Zombienet for automatic registration:"
echo "  make net"
echo ""
echo "========================================="
echo "Step 4: Run Worker with Real Chains"
echo "========================================="
echo ""
echo "Edit worker/.env:"
echo "  RPC_A=ws://127.0.0.1:8845"
echo "  RPC_B=ws://127.0.0.1:8847"
echo "  LIGHTHOUSE_KEY=your_api_key"
echo ""
echo "Run worker:"
echo "  cd worker && npm start"
echo ""
echo "========================================="
echo "Quick Demo (No Chains Needed)"
echo "========================================="
echo ""
echo "To see the IVS algorithm in action without chains:"
echo "  cd worker && DEMO=1 npm start"
echo ""
echo "This demonstrates:"
echo "  - CKKS homomorphic encryption"
echo "  - BFS-based IVS computation"
echo "  - Exponential decay weighting"
echo "  - Mock contact graph with 5 users"
echo ""
echo "========================================="
echo ""

# Ask user what they want to do
echo "What would you like to do?"
echo ""
echo "  1) Run demo again (quick, no build needed)"
echo "  2) Start building chains (takes 30-60 min)"
echo "  3) Show full instructions"
echo "  4) Exit"
echo ""
read -p "Enter choice (1-4): " choice

case $choice in
    1)
        echo ""
        echo "Running demo..."
        cd worker && DEMO=1 npm start
        ;;
    2)
        echo ""
        echo "Starting build process..."
        echo "This will take 30-60 minutes. Press Ctrl+C to cancel."
        sleep 3
        make build
        ;;
    3)
        echo ""
        cat README.md
        ;;
    4)
        echo "Goodbye!"
        ;;
    *)
        echo "Invalid choice"
        ;;
esac
