name: EVM test suite

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  isdraft:
    uses: ./.github/workflows/reusable-isdraft.yml
  preflight:
    needs: isdraft
    uses: ./.github/workflows/reusable-preflight.yml

  evm-test-suite:
    needs: [preflight]
    runs-on: ${{ needs.preflight.outputs.RUNNER }}
    if: ${{ needs.preflight.outputs.changes_rust }}
    timeout-minutes: 60
    container:
      image: ${{ needs.preflight.outputs.IMAGE }}
    env:
      # Enable debug assertions since we are running optimized builds for testing
      # but still want to have debug assertions.
      RUSTFLAGS: "-C debug-assertions"
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: script
        run: |
          forklift cargo build --locked --release -p pallet-revive-eth-rpc --bin eth-rpc
          forklift cargo build --locked --release -p revive-dev-node --bin revive-dev-node

      - name: Checkout evm-tests
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: paritytech/evm-test-suite
          ref: d20230d0a70ad1159ee75b4c56a47e85173f19e5
          path: evm-test-suite

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: script
        run: |
          echo "Change to the evm-test-suite directory"
          cd evm-test-suite

          deno --version

          echo "Check that binaries are in place"
          export REVIVE_DEV_NODE_PATH=$(readlink -f ../target/release/revive-dev-node)
          export ETH_RPC_PATH=$(readlink -f ../target/release/eth-rpc)
          echo $REVIVE_DEV_NODE_PATH $ETH_RPC_PATH

          echo "== Running pvm tests ==j"
          START_REVIVE_DEV_NODE=true START_ETH_RPC=true deno task test:pvm

          echo "== Running evm tests =="
          START_REVIVE_DEV_NODE=true START_ETH_RPC=true deno task test:evm

      - name: Collect tests results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: evm-test-suite-${{ github.sha }}
          path: evm-test-suite/test-logs/matter-labs-tests.log

  confirm-required-test-evm-jobs-passed:
    runs-on: ubuntu-latest
    name: All test misc tests passed
    # If any new job gets added, be sure to add it to this array
    needs:
      - evm-test-suite
    if: always() && !cancelled()
    steps:
      - run: |
          tee resultfile <<< '${{ toJSON(needs) }}'
          FAILURES=$(cat resultfile | grep '"result": "failure"' | wc -l)
          if [ $FAILURES -gt 0 ]; then
            echo "### At least one required job failed ❌" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo '### Good job! All the required jobs passed 🚀' >> $GITHUB_STEP_SUMMARY
          fi