#!/usr/bin/env bash

echo "========================================="
echo "Parachain Registration Instructions"
echo "========================================="
echo ""
echo "To register your parachains with the relay chain, follow these steps:"
echo ""
echo "1. Open Polkadot.js Apps connected to your relay chain:"
echo "   https://polkadot.js.org/apps/?rpc=ws://127.0.0.1:9945#/sudo"
echo ""
echo "2. Go to Developer > Sudo"
echo ""
echo "3. For each parachain (Disease-A: 2000, Disease-B: 2001, Aggregator: 3000):"
echo ""
echo "   a) Select: parasSudoWrapper > sudoScheduleParaInitialize(id, genesis)"
echo ""
echo "      - id: [ParaId] (e.g., 2000)"
echo "      - genesisHead: [Upload para-XXXX-genesis-state file]"
echo "      - validationCode: [Upload para-XXXX-wasm file]"
echo "      - paraKind: Yes (Parachain)"
echo ""
echo "      Submit the transaction (use Alice's sudo account)"
echo ""
echo "   b) Wait for the transaction to be included in a block"
echo ""
echo "4. Parachain artifacts locations:"
echo ""
echo "   Disease-A (ParaId: 2000):"
echo "     - State: chain/disease-a/para-2000-genesis-state"
echo "     - Wasm:  chain/disease-a/para-2000-wasm"
echo ""
echo "   Disease-B (ParaId: 2001):"
echo "     - State: chain/disease-b/para-2001-genesis-state"
echo "     - Wasm:  chain/disease-b/para-2001-wasm"
echo ""
echo "   Aggregator (ParaId: 3000):"
echo "     - State: chain/aggregator/para-3000-genesis-state"
echo "     - Wasm:  chain/aggregator/para-3000-wasm"
echo ""
echo "5. After registration, wait 2-3 relay chain blocks for parachains to start producing blocks"
echo ""
echo "6. Verify in Polkadot.js Apps > Network > Parachains"
echo ""
echo "========================================="
echo "Alternative: Use Zombienet for automatic registration"
echo "========================================="
echo ""
echo "Run: make net"
echo ""
echo "This will spawn the entire network with automatic parachain registration"
echo "using the Zombienet configuration."
echo ""
